### ISSUE TITLE
add bookmarkable bookmarklet link to the page

### ISSUE THREAD

**Issue by bburdette** [Janiczek/ellies#3]
It would be nice if there was a link on the ellie catalog page you could drag straight to your toolbar and then use to add ellies to the catalog.  That's how [mozilla's bookmarklet doc](https://support.mozilla.org/en-US/kb/bookmarklets-perform-common-web-page-tasks) says its supposed to work.  The way it is now, dragging the 'this bookmarklet' link to the toolbar just gives you a link to the source, not a bookmarklet that does something.

Also, maybe a link to explanations of bookmarklets in general?  This was my first bookmarklet experience and it took me a while to get it sorted.

**Comment by Janiczek** [comment]
I wanted to do that and can't do it because of Elm disallowing `javascript:` links :(
https://github.com/elm/virtual-dom/blob/master/src/Elm/Kernel/VirtualDom.js#L292-L302

**Comment by Janiczek** [comment]
@jackwilsdon this is now live, thanks!
@bburdette WDYT? Enough to close? :)

**Comment by bburdette** [comment]
Nice!  What would be even more clear to me would be this:

Drag this link to your bookmark bar:  [Add To Ellie Catalog](http://not.the.real.link.com).  Then when you find an interesting Ellie, click it!

Up to you if you want to change it.  This is cool, I'm already thinking about how to use a bookmarklet for my own stuff!

**Comment by Janiczek** [comment]
@bburdette @jackwilsdon just a heads up - this doesn't work with `--optimize` Elm builds, just with the normal ones :man_facepalming: I'll have to revert this.

**Comment by Janiczek** [comment]
I'll work around this with a WebComponent: https://ellie-app.com/hwbBHmqLQ8Ra1

**Comment by Janiczek** [comment]
@bburdette I've now deployed a version with a proper bookmarklet and also with your suggested copy! Thanks 🙇
