### ISSUE TITLE
site is down?

### ISSUE THREAD

**Issue by bburdette** [Janiczek/ellies#4]
https://janiczek-ellies.builtwithdark.com/

site does a

GET | https://janiczek-ellies.darksa.com/-hyuv8t7uhbjc7lzfvj_qkcsvbq/d0pqnyebi5/elm.js?v=1

which has a 401 unauthorized result.

**Comment by Janiczek** [comment]
Hey there, I don't see this issue. I'm getting 200 Success on the Elm file 🤔 All seems to work well for me. Can you recheck?

**Comment by bburdette** [comment]
My bad, I had a fake token set up for debugging another site.  Added appropriate filters to the ModHeader plugin and now all is well.  Sorry about that!
